// Generated by https://quicktype.io

export interface NopayInfoTblModel {
    totalNoPay:     Period;
    setOff:         Period;
    above30SetOff:  Period;
    foreignSetoff:  Period;
    totalSetoff:    Period;
    netNopayLeaves: Period;
}

export interface Period {
    years:  number;
    months: number;
    days:   number;
}
