// Generated by https://quicktype.io

export interface SalaryInfoTblModel {
    annualConsolidatedSalary: SalaryModel;
    earnedIncrement:          SalaryModel;
}

export interface SalaryModel {
    current: number;
    at2020:  number;
}
